### PR TITLE
SCP-2242 Build with Haskell Stack

### PR DESCRIPTION
**Pull request by koslambrou**
Project can now be build with Haskell Stack. Instructions were added to README on how to do so.

### CODE REVIEW

**Comment by silky** [comment]
Works for me!

The only thing I wonder is if we're creating a lot of things to maintain when we change things over on the plutus side. (For example, if we bump a version of a dependency over there). I'm not sure there's any easy answer, but I just feel slightly concerned that there are now two spots to manage the plutus commit hash + associated packages, combined with having to make sure this project remains compatible with the new docker-hub devcontainer that's pushed, etc.

I suppose we just need a bit of a combined CI story; maybe that would be enough.

I'm happy if everyone else is :)

**Review by silky — APPROVED** [review]
LGTM (I note that it looks like this PR incorporates the other one adding nix.)

**Comment by michaelpj** [comment]
Did Jann ask for this? Personally I agree that we should support as few configurations as possible to keep things maintainable. So I think it would be quite reasonable to only support cabal.

**Comment by koslambrou** [comment]
After discussion, `Haskell Stack` will not be supported for the time being.

**Pull request closed without merging**
